### ISSUE TITLE
Compatible with Media in core

### ISSUE THREAD

**Issue by soniCaH** [vasilyyaremchuk/pull_quote_demo_pull_quote_demo#1]
Hey, I saw the slides of your presentation on DrupalEurope and was wondering if this works with the core Media module in Drupal 8.4+

When creating a media type (instead of bundle), you are now obliged to select a Source plugin (Image, Video, Document...).
Does this mean we need to create a "Text" Source plugin or something similar?

**Comment by vasilyyaremchuk** [comment]
HI Kevin,
I didn't try that approach with native core media module but use contributed Media Entity module instead.
I think that your idea is good about Text source but better to use Media Entity with the ability to select generic media option.

**Comment by soniCaH** [comment]
Ok thanks!
